// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3eizSKEwkUnH1Y5Xcum3fVgczGgPAFkk',
    appId: '1:264737328165:web:d8744f8fc1c188d9ddc3cc',
    messagingSenderId: '264737328165',
    projectId: 'offibox-prod',
    authDomain: 'offibox-prod.firebaseapp.com',
    storageBucket: 'offibox-prod.firebasestorage.app',
    measurementId: 'G-E1FP98K8WE',
  );

  /// Client ID OAuth 2.0 pour Google Sign-In sur le web. Récupérer dans Firebase Console :
  /// Authentication > Sign-in method > Google > Web client ID (format: 264737328165-xxx.apps.googleusercontent.com).
  static const String? webGoogleClientId = '264737328165-cskk83jevrjrc94veihvcfo3jola2p63.apps.googleusercontent.com';

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi1AhMabx9PZYeNnZxZqfyogtrmEWp8pA',
    appId: '1:264737328165:android:9156ce010d5fd07cddc3cc',
    messagingSenderId: '264737328165',
    projectId: 'offibox-prod',
    storageBucket: 'offibox-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaZaKHZnGylAJo2qScOQgbSZNy6g7EKlE',
    appId: '1:264737328165:ios:6b20effe963daa3cddc3cc',
    messagingSenderId: '264737328165',
    projectId: 'offibox-prod',
    storageBucket: 'offibox-prod.firebasestorage.app',
    iosClientId: '264737328165-fp2vtfqfmlvs59di3cb6ku7o82v57rqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.offibox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaZaKHZnGylAJo2qScOQgbSZNy6g7EKlE',
    appId: '1:264737328165:ios:6b20effe963daa3cddc3cc',
    messagingSenderId: '264737328165',
    projectId: 'offibox-prod',
    storageBucket: 'offibox-prod.firebasestorage.app',
    iosClientId: '264737328165-fp2vtfqfmlvs59di3cb6ku7o82v57rqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.offibox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3eizSKEwkUnH1Y5Xcum3fVgczGgPAFkk',
    appId: '1:264737328165:web:e3cc7f1f356f45beddc3cc',
    messagingSenderId: '264737328165',
    projectId: 'offibox-prod',
    authDomain: 'offibox-prod.firebaseapp.com',
    storageBucket: 'offibox-prod.firebasestorage.app',
    measurementId: 'G-TXG2D6HQBG',
  );
}
